spring:
  application:
    name: eataku

  datasource:
    url: jdbc:mysql://db-eataku.ct2o2ceg2rjv.ap-southeast-2.rds.amazonaws.com:3306/eatakudb
    username: admin
    password: eataku12
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    properties:
      hibernate:
        '[format_sql]': true
  mail:
    host: smtp.gmail.com
    port: 587
    username: noReply.eataku@gmail.com
    password: jacvjbumalubfrcu
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

coolsms:
  api:
    key: "NCSSWFPPRCG3IEF7"
    secret: "ZOAXIYXOCXX5KSBH3BK00WPPGLSOQQZS"
    number: 01090184610

cloud:
  aws:
    credentials:
      access-key: ncp_iam_BPASKRWxSTDaP4FehYOM
      secret-key: ncp_iam_BPKSKRJHikqfZbqxTJPD0W8tvPqhNKMS6T
    stack:
      auto: false
    region:
      static: kr-standard
    s3:
      endpoint: https://kr.object.ncloudstorage.com/
      bucket: oshino-file

kakao:
  client_id: 09e07802c737310d172f056dfbaf323b
  #  redirect_uri: https://eataku.kr/callback
  redirect_uri: http://localhost:8080/callback